version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 339712928920.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t causeworkaws-chathu1 .
      - docker tag causeworkaws-chathu1:latest 339712928920.dkr.ecr.eu-north-1.amazonaws.com/causeworkaws-chathu1:latest
  post_build:
    commands:
      - docker push 339712928920.dkr.ecr.eu-north-1.amazonaws.com/causeworkaws-chathu1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
